# remap prefix to Ctrl-s
set -g prefix C-s

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# enable mouse clicks
set -g mouse on

# clock mode
setw -g clock-mode-colour gray

# copy mode
setw -g mode-style 'fg=black bg=magenta bold'

# panes
set -g pane-border-style 'fg=gray'
set -g pane-active-border-style 'fg=magenta'

# statusbar
set -g status-position bottom
set -g status-justify centre
set -g status-style 'fg=magenta'

set -g status-left ''
set -g status-left-length 10

set -g status-right ''
set -g status-right-length 10

setw -g window-status-current-style 'fg=gray bg=magenta'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=magenta bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=gray]#F '

setw -g window-status-bell-style 'fg=gray bg=magenta bold'

# add space above statusbar
set -Fg 'status-format[1]' '#{status-format[0]}'
set -g 'status-format[0]' ''
set -g status 2

# messages
set -g message-style 'fg=gray bg=magenta bold'
